### ISSUE TITLE
Webstorm Project Updating never stops

### ISSUE THREAD

**Issue by janlem** [Turbo87/intellij-emberjs#36]
Great plugin so far. Thanks!
A small issue I face: while having the plugin active the project explorer of Webstorm never stops updating the project when expanding the project folder. I can access all files via double-shift, but a usable project explorer would be nice. If you need anymore clarification, just ask!
Thanks again, keep up the good work!

PS: I'm using Webstorm 10.0.4, I hope that counts as supported ;-)
![webstormemberpluginproblem](https://cloud.githubusercontent.com/assets/2778046/12883797/625cf996-ce5a-11e5-8e7e-da941a38bd12.PNG)

**Comment by Turbo87** [comment]
hmm interesting, I haven't noticed any such issues when I tested it with WebStorm. I'll see if I can reproduce it.

**Comment by raido** [comment]
I have the same issue with PHPStorm 9.0.2 - i have tried rm -rf .idea in project root, still the same.

**Comment by raido** [comment]
@Turbo87 Maybe this log helps - https://gist.github.com/raido/3c41f33fe9738e0457f3

**Comment by raido** [comment]
@Turbo87 

Update: https://intellij-support.jetbrains.com/hc/en-us/community/posts/206332899-Why-some-folders-don-t-display-subfolders-files-in-Project-View-in-WebStorm-?page=1#community_comment_207342339

The problem with PHPStorm seems to be that plugin adds "public" folder as source folder with type "java-resource", but PHPStorm does not have handler for dealing with such a resource and thus fails with error like in my log.

https://github.com/Turbo87/intellij-emberjs/blob/master/src/main/kotlin/com/emberjs/project/EmberProjectComponent.kt#L134

.idea/<project-name>.iml
```
<sourceFolder url="file://$MODULE_DIR$/public" type="java-resource" />
```

**Comment by Turbo87** [comment]
hmm, that is quite surprising because it seemed to work just fine in WebStorm for me. unfortunately I haven't found out how to determine the IDE name and version programmatically to conditionally use the resource folder only on IntelliJ.

**Comment by raido** [comment]
If i mark public as resource via context menu in PHPStorm, it gets added to .idea/webResources file instead of .idea/project-name.iml where the plugin originally adds it.

**Comment by raido** [comment]
@Turbo87 I tested PR with PHPStorm 9.0.2 and it worked fine did rm -rf ./idea, installed plugin and project navigator worked fine.

**Comment by Turbo87** [comment]
should be fixed by #42

**Comment by janlem** [comment]
I'm still seeing the problem in version 1.4.2 of the plugin. Will there be a newer version available through the Webstorm Plugin Repository that contains the fix?

**Comment by Turbo87** [comment]
@janlem the patch hasn't been released yet, but I'll publish it soon

**Comment by janlem** [comment]
Ok, thanks for letting me know. And thank you for your effort!

**Comment by janlem** [comment]
Thanks again for the fix. Version 1.5.0 works for me, too!
